# Generated by Django 4.0.3 on 2022-04-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSDSApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
